from __future__ import annotations

from dataclasses import dataclass
from typing import TypeAlias

from slope_stab.models import (
    AnalysisInput,
    AutoRefineSearchInput,
    CmaesGlobalSearchInput,
    CuckooGlobalSearchInput,
    DirectGlobalSearchInput,
    GeometryInput,
    GroundwaterHuInput,
    GroundwaterInput,
    LoadsInput,
    MaterialInput,
    PrescribedCircleInput,
    ProjectInput,
    SearchInput,
    SearchLimitsInput,
    UniformSurchargeInput,
)


@dataclass(frozen=True)
class PrescribedVerificationCase:
    case_type: str
    name: str
    project: ProjectInput
    expected_fos: float
    fos_tolerance: float
    expected_driving_moment: float | None = None
    expected_resisting_moment: float | None = None
    moment_rel_tolerance: float | None = None
    analysis_method: str = "bishop_simplified"


@dataclass(frozen=True)
class AutoRefineVerificationCase:
    case_type: str
    name: str
    project: ProjectInput
    expected_fos: float
    fos_tolerance: float
    expected_radius: float
    radius_rel_tolerance: float
    expected_center: tuple[float, float]
    expected_left: tuple[float, float]
    expected_right: tuple[float, float]
    endpoint_abs_tolerance: float
    analysis_method: str = "bishop_simplified"


@dataclass(frozen=True)
class GlobalSearchBenchmarkVerificationCase:
    case_type: str
    search_method: str
    name: str
    project: ProjectInput
    benchmark_fos: float
    margin: float
    analysis_method: str = "bishop_simplified"


VerificationCase: TypeAlias = (
    PrescribedVerificationCase
    | AutoRefineVerificationCase
    | GlobalSearchBenchmarkVerificationCase
)


VERIFICATION_CASES: tuple[VerificationCase, ...] = (
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 1",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=29.07,
                yc=55.495,
                r=30.4956368485163,
                x_left=30.02888427029,
                y_left=25.014442135145,
                x_right=51.6518254752929,
                y_right=35.0,
            ),
        ),
        expected_fos=0.986763,
        fos_tolerance=1e-4,
        expected_driving_moment=11867.3,
        expected_resisting_moment=11710.2,
        moment_rel_tolerance=1e-3,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 2",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=13.689,
                yc=25.558,
                r=15.989,
                x_left=10.0005216402222,
                y_left=10.0002608201111,
                x_right=27.4990237870903,
                y_right=17.5,
            ),
        ),
        expected_fos=2.11283,
        fos_tolerance=5e-4,
        expected_driving_moment=5715.12,
        expected_resisting_moment=12075.1,
        moment_rel_tolerance=1e-3,
    ),
    AutoRefineVerificationCase(
        case_type="auto_refine_parity",
        name="Case 3",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="auto_refine_circular",
                auto_refine_circular=AutoRefineSearchInput(
                    divisions_along_slope=20,
                    circles_per_division=10,
                    iterations=10,
                    divisions_to_use_next_iteration_pct=50.0,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        expected_fos=0.986442,
        fos_tolerance=0.001,
        expected_radius=26.793,
        radius_rel_tolerance=0.10,
        expected_center=(30.259, 51.792),
        expected_left=(30.0, 25.0),
        expected_right=(51.137, 35.0),
        endpoint_abs_tolerance=0.20,
    ),
    AutoRefineVerificationCase(
        case_type="auto_refine_parity",
        name="Case 4",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="auto_refine_circular",
                auto_refine_circular=AutoRefineSearchInput(
                    divisions_along_slope=30,
                    circles_per_division=15,
                    iterations=15,
                    divisions_to_use_next_iteration_pct=50.0,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        expected_fos=1.234670,
        fos_tolerance=0.001,
        expected_radius=43.234,
        radius_rel_tolerance=0.10,
        expected_center=(21.024, 67.292),
        expected_left=(30.0, 25.0),
        expected_right=(58.068, 45.0),
        endpoint_abs_tolerance=0.20,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 3 (Surcharge 50kPa Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=27.6485174011401,
                yc=61.5854419184982,
                r=36.6607805519873,
                x_left=30.0003512982362,
                y_left=25.0001756491181,
                x_right=52.891875115183,
                y_right=35.0,
            ),
            loads=LoadsInput(
                uniform_surcharge=UniformSurchargeInput(
                    magnitude_kpa=50.0,
                    placement="crest_infinite",
                )
            ),
        ),
        expected_fos=0.903987,
        fos_tolerance=0.005,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 5 (Water Surfaces Hu=1 Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=30.0, x_toe=18.0, y_toe=15.0),
            material=MaterialInput(gamma=18.82, c=41.65, phi_deg=15.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=30,
                tolerance=0.0001,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=27.7816099623784,
                yc=45.4165765413013,
                r=31.9496411014504,
                x_left=18.0011387032865,
                y_left=15.0007591355243,
                x_right=57.9854921577304,
                y_right=35.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 15.0), (18.0, 15.0), (30.0, 23.0), (48.0, 29.0), (66.0, 32.0)),
                    hu=GroundwaterHuInput(mode="custom", value=1.0),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=1.116190,
        fos_tolerance=0.001,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 5 (Water Surfaces Hu=Auto Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=30.0, x_toe=18.0, y_toe=15.0),
            material=MaterialInput(gamma=18.82, c=41.65, phi_deg=15.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=30,
                tolerance=0.0001,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=27.435184386849,
                yc=45.2985429525467,
                r=31.7351010556423,
                x_left=17.9951137322134,
                y_left=15.0,
                x_right=57.4527900886098,
                y_right=35.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 15.0), (18.0, 15.0), (30.0, 23.0), (48.0, 29.0), (66.0, 32.0)),
                    hu=GroundwaterHuInput(mode="auto", value=None),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=1.157200,
        fos_tolerance=0.001,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 6 (Ru Coefficient Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=-30.0, l=60.0, x_toe=10.0, y_toe=40.0),
            material=MaterialInput(gamma=18.0, c=10.8, phi_deg=40.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=30,
                tolerance=0.0001,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=69.4716746369335,
                yc=90.1503711737807,
                r=80.1517372879095,
                x_left=6.94774912515767,
                y_left=40.0,
                x_right=69.9992594556713,
                y_right=10.0003702721644,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="ru_coefficient",
                    ru=0.5,
                )
            ),
        ),
        expected_fos=1.001250,
        fos_tolerance=0.005,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 7 (Ponded Water Hu=Auto Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=6.0, l=2.0, x_toe=5.0, y_toe=3.0),
            material=MaterialInput(gamma=16.0, c=12.0, phi_deg=38.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=50,
                tolerance=0.001,
                max_iter=75,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=1.65885679531231,
                yc=9.0,
                r=6.865877145366,
                x_left=5.00078365866115,
                y_left=3.00235097598346,
                x_right=8.52473394067831,
                y_right=9.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 4.609), (5.53621, 4.60862), (6.44028, 7.32085), (12.0, 8.0)),
                    hu=GroundwaterHuInput(mode="auto", value=None),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=0.940158,
        fos_tolerance=0.001,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        name="Case 8 (Ponded Water Hu=Auto Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=6.0, l=7.0, x_toe=5.0, y_toe=3.0),
            material=MaterialInput(gamma=16.0, c=12.0, phi_deg=38.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=50,
                tolerance=0.001,
                max_iter=75,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=5.81157572491755,
                yc=13.042352415468,
                r=10.0749729401736,
                x_left=5.00012832564169,
                y_left=3.00010999340716,
                x_right=15.0400353306367,
                y_right=9.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 7.184), (9.8819, 7.18448), (20.0, 9.0)),
                    hu=GroundwaterHuInput(mode="auto", value=None),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=2.511620,
        fos_tolerance=0.001,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="global_search_benchmark",
        search_method="direct_global_circular",
        name="Case 2 (Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="direct_global_circular",
                direct_global_circular=DirectGlobalSearchInput(
                    max_iterations=90,
                    max_evaluations=1200,
                    min_improvement=1e-4,
                    stall_iterations=12,
                    min_rectangle_half_size=1e-3,
                    search_limits=SearchLimitsInput(x_min=2.5, x_max=40.0),
                ),
            ),
        ),
        benchmark_fos=2.11283,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="global_search_benchmark",
        search_method="direct_global_circular",
        name="Case 3 (Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="direct_global_circular",
                direct_global_circular=DirectGlobalSearchInput(
                    max_iterations=120,
                    max_evaluations=1800,
                    min_improvement=1e-4,
                    stall_iterations=15,
                    min_rectangle_half_size=1e-3,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        benchmark_fos=0.986442,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="global_search_benchmark",
        search_method="direct_global_circular",
        name="Case 4 (Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="direct_global_circular",
                direct_global_circular=DirectGlobalSearchInput(
                    max_iterations=140,
                    max_evaluations=2200,
                    min_improvement=1e-4,
                    stall_iterations=18,
                    min_rectangle_half_size=1e-3,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        benchmark_fos=1.234670,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cuckoo_global_search_benchmark",
        search_method="cuckoo_global_circular",
        name="Case 2 (Cuckoo Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cuckoo_global_circular",
                cuckoo_global_circular=CuckooGlobalSearchInput(
                    population_size=40,
                    max_iterations=200,
                    max_evaluations=4000,
                    discovery_rate=0.20,
                    levy_beta=1.5,
                    alpha_max=0.5,
                    alpha_min=0.05,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=0,
                    post_polish=True,
                    search_limits=SearchLimitsInput(x_min=2.5, x_max=40.0),
                ),
            ),
        ),
        benchmark_fos=2.11283,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cuckoo_global_search_benchmark",
        search_method="cuckoo_global_circular",
        name="Case 3 (Cuckoo Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cuckoo_global_circular",
                cuckoo_global_circular=CuckooGlobalSearchInput(
                    population_size=40,
                    max_iterations=200,
                    max_evaluations=5000,
                    discovery_rate=0.20,
                    levy_beta=1.5,
                    alpha_max=0.5,
                    alpha_min=0.05,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=0,
                    post_polish=True,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        benchmark_fos=0.986442,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cuckoo_global_search_benchmark",
        search_method="cuckoo_global_circular",
        name="Case 4 (Cuckoo Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cuckoo_global_circular",
                cuckoo_global_circular=CuckooGlobalSearchInput(
                    population_size=50,
                    max_iterations=250,
                    max_evaluations=7000,
                    discovery_rate=0.20,
                    levy_beta=1.5,
                    alpha_max=0.5,
                    alpha_min=0.05,
                    min_improvement=1e-4,
                    stall_iterations=30,
                    seed=0,
                    post_polish=True,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        benchmark_fos=1.234670,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cmaes_global_search_benchmark",
        search_method="cmaes_global_circular",
        name="Case 2 (CMAES Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cmaes_global_circular",
                cmaes_global_circular=CmaesGlobalSearchInput(
                    max_evaluations=4500,
                    direct_prescan_evaluations=600,
                    cmaes_population_size=8,
                    cmaes_max_iterations=180,
                    cmaes_restarts=2,
                    cmaes_sigma0=0.15,
                    polish_max_evaluations=80,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=1,
                    post_polish=True,
                    invalid_penalty=1e6,
                    nonconverged_penalty=1e5,
                    search_limits=SearchLimitsInput(x_min=2.5, x_max=40.0),
                ),
            ),
        ),
        benchmark_fos=2.11283,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cmaes_global_search_benchmark",
        search_method="cmaes_global_circular",
        name="Case 3 (CMAES Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cmaes_global_circular",
                cmaes_global_circular=CmaesGlobalSearchInput(
                    max_evaluations=5500,
                    direct_prescan_evaluations=800,
                    cmaes_population_size=8,
                    cmaes_max_iterations=200,
                    cmaes_restarts=2,
                    cmaes_sigma0=0.15,
                    polish_max_evaluations=100,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=1,
                    post_polish=True,
                    invalid_penalty=1e6,
                    nonconverged_penalty=1e5,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        benchmark_fos=0.986442,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cmaes_global_search_benchmark",
        search_method="cmaes_global_circular",
        name="Case 4 (CMAES Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="bishop_simplified",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cmaes_global_circular",
                cmaes_global_circular=CmaesGlobalSearchInput(
                    max_evaluations=7000,
                    direct_prescan_evaluations=1200,
                    cmaes_population_size=10,
                    cmaes_max_iterations=250,
                    cmaes_restarts=3,
                    cmaes_sigma0=0.15,
                    polish_max_evaluations=120,
                    min_improvement=1e-4,
                    stall_iterations=30,
                    seed=1,
                    post_polish=True,
                    invalid_penalty=1e6,
                    nonconverged_penalty=1e5,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        benchmark_fos=1.234670,
        margin=0.01,
    ),
)


SPENCER_VERIFICATION_CASES: tuple[VerificationCase, ...] = (
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 2 (Spencer Prescribed Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=13.689,
                yc=25.558,
                r=15.989,
                x_left=10.0005216402222,
                y_left=10.0002608201111,
                x_right=27.4990237870903,
                y_right=17.5,
            ),
        ),
        expected_fos=2.11168,
        fos_tolerance=0.005,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 3 (Spencer Prescribed Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=30.2546073537702,
                yc=51.7886948308462,
                r=26.7899128131506,
                x_left=29.9991512988288,
                y_left=25.0,
                x_right=51.1313684630259,
                y_right=35.0,
            ),
        ),
        expected_fos=0.985334,
        fos_tolerance=0.002,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 4 (Spencer Prescribed Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=22.5811777177525,
                yc=64.3127170691117,
                r=39.9948933227408,
                x_left=30.0195115924048,
                y_left=25.0156092739238,
                x_right=57.6041766085651,
                y_right=45.0,
            ),
        ),
        expected_fos=1.23141,
        fos_tolerance=0.002,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 3 (Spencer Surcharge 50kPa Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=27.6485174011401,
                yc=61.5854419184982,
                r=36.6607805519873,
                x_left=30.0003512982362,
                y_left=25.0001756491181,
                x_right=52.891875115183,
                y_right=35.0,
            ),
            loads=LoadsInput(
                uniform_surcharge=UniformSurchargeInput(
                    magnitude_kpa=50.0,
                    placement="crest_infinite",
                )
            ),
        ),
        expected_fos=0.903192,
        fos_tolerance=0.005,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 5 (Spencer Water Surfaces Hu=1 Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=30.0, x_toe=18.0, y_toe=15.0),
            material=MaterialInput(gamma=18.82, c=41.65, phi_deg=15.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=30,
                tolerance=0.0001,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=27.6258499840977,
                yc=45.3623063863069,
                r=31.8505670075193,
                x_left=18.0011387032865,
                y_left=15.0007591355243,
                x_right=57.7436391635308,
                y_right=35.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 15.0), (18.0, 15.0), (30.0, 23.0), (48.0, 29.0), (66.0, 32.0)),
                    hu=GroundwaterHuInput(mode="custom", value=1.0),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=1.116480,
        fos_tolerance=0.001,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 5 (Spencer Water Surfaces Hu=Auto Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=30.0, x_toe=18.0, y_toe=15.0),
            material=MaterialInput(gamma=18.82, c=41.65, phi_deg=15.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=30,
                tolerance=0.0001,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=27.435184386849,
                yc=45.2985429525467,
                r=31.7351010556423,
                x_left=17.9951137322134,
                y_left=15.0,
                x_right=57.4527900886098,
                y_right=35.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 15.0), (18.0, 15.0), (30.0, 23.0), (48.0, 29.0), (66.0, 32.0)),
                    hu=GroundwaterHuInput(mode="auto", value=None),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=1.157020,
        fos_tolerance=0.001,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 6 (Spencer Ru Coefficient Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=-30.0, l=60.0, x_toe=10.0, y_toe=40.0),
            material=MaterialInput(gamma=18.0, c=10.8, phi_deg=40.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=30,
                tolerance=0.0001,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=69.6211856957322,
                yc=90.016174054555,
                r=80.0166969745064,
                x_left=7.16276650620701,
                y_left=40.0,
                x_right=69.9992594556713,
                y_right=10.0003702721644,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="ru_coefficient",
                    ru=0.5,
                )
            ),
        ),
        expected_fos=1.018880,
        fos_tolerance=0.005,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 7 (Spencer Ponded Water Hu=Auto Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=6.0, l=2.0, x_toe=5.0, y_toe=3.0),
            material=MaterialInput(gamma=16.0, c=12.0, phi_deg=38.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=50,
                tolerance=0.001,
                max_iter=75,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=2.47419041573854,
                yc=10.3792666017876,
                r=7.75902007436276,
                x_left=5.01615097845115,
                y_left=3.04845293535344,
                x_right=10.1096351411987,
                y_right=9.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 4.609), (5.53621, 4.60862), (6.44028, 7.32085), (12.0, 8.0)),
                    hu=GroundwaterHuInput(mode="auto", value=None),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=1.049400,
        fos_tolerance=0.001,
    ),
    PrescribedVerificationCase(
        case_type="prescribed_benchmark",
        analysis_method="spencer",
        name="Case 8 (Spencer Ponded Water Hu=Auto Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=6.0, l=7.0, x_toe=5.0, y_toe=3.0),
            material=MaterialInput(gamma=16.0, c=12.0, phi_deg=38.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=50,
                tolerance=0.001,
                max_iter=75,
                f_init=1.0,
            ),
            prescribed_surface=PrescribedCircleInput(
                xc=5.81157572491755,
                yc=13.042352415468,
                r=10.0749729401736,
                x_left=5.00012832564169,
                y_left=3.00010999340716,
                x_right=15.0400353306367,
                y_right=9.0,
            ),
            loads=LoadsInput(
                groundwater=GroundwaterInput(
                    model="water_surfaces",
                    surface=((0.0, 7.184), (9.8819, 7.18448), (20.0, 9.0)),
                    hu=GroundwaterHuInput(mode="auto", value=None),
                    gamma_w=9.81,
                )
            ),
        ),
        expected_fos=2.505910,
        fos_tolerance=0.001,
    ),
    AutoRefineVerificationCase(
        case_type="auto_refine_parity",
        analysis_method="spencer",
        name="Case 3 (Spencer Auto-Refine Parity)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="auto_refine_circular",
                auto_refine_circular=AutoRefineSearchInput(
                    divisions_along_slope=20,
                    circles_per_division=10,
                    iterations=10,
                    divisions_to_use_next_iteration_pct=50.0,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        expected_fos=0.985334,
        fos_tolerance=0.002,
        expected_radius=26.7899128131506,
        radius_rel_tolerance=0.12,
        expected_center=(30.2546073537702, 51.7886948308462),
        expected_left=(29.9991512988288, 25.0),
        expected_right=(51.1313684630259, 35.0),
        endpoint_abs_tolerance=0.30,
    ),
    AutoRefineVerificationCase(
        case_type="auto_refine_parity",
        analysis_method="spencer",
        name="Case 4 (Spencer Auto-Refine Parity)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="auto_refine_circular",
                auto_refine_circular=AutoRefineSearchInput(
                    divisions_along_slope=30,
                    circles_per_division=15,
                    iterations=15,
                    divisions_to_use_next_iteration_pct=50.0,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        expected_fos=1.23141,
        fos_tolerance=0.002,
        expected_radius=39.9948933227408,
        radius_rel_tolerance=0.12,
        expected_center=(22.5811777177525, 64.3127170691117),
        expected_left=(30.0195115924048, 25.0156092739238),
        expected_right=(57.6041766085651, 45.0),
        endpoint_abs_tolerance=0.30,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="global_search_benchmark",
        analysis_method="spencer",
        search_method="direct_global_circular",
        name="Case 2 (Spencer Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="direct_global_circular",
                direct_global_circular=DirectGlobalSearchInput(
                    max_iterations=90,
                    max_evaluations=1200,
                    min_improvement=1e-4,
                    stall_iterations=12,
                    min_rectangle_half_size=1e-3,
                    search_limits=SearchLimitsInput(x_min=2.5, x_max=40.0),
                ),
            ),
        ),
        benchmark_fos=2.11168,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="global_search_benchmark",
        analysis_method="spencer",
        search_method="direct_global_circular",
        name="Case 3 (Spencer Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="direct_global_circular",
                direct_global_circular=DirectGlobalSearchInput(
                    max_iterations=120,
                    max_evaluations=1800,
                    min_improvement=1e-4,
                    stall_iterations=15,
                    min_rectangle_half_size=1e-3,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        benchmark_fos=0.985334,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="global_search_benchmark",
        analysis_method="spencer",
        search_method="direct_global_circular",
        name="Case 4 (Spencer Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="direct_global_circular",
                direct_global_circular=DirectGlobalSearchInput(
                    max_iterations=140,
                    max_evaluations=2200,
                    min_improvement=1e-4,
                    stall_iterations=18,
                    min_rectangle_half_size=1e-3,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        benchmark_fos=1.23141,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cuckoo_global_search_benchmark",
        analysis_method="spencer",
        search_method="cuckoo_global_circular",
        name="Case 2 (Spencer Cuckoo Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cuckoo_global_circular",
                cuckoo_global_circular=CuckooGlobalSearchInput(
                    population_size=40,
                    max_iterations=200,
                    max_evaluations=4000,
                    discovery_rate=0.20,
                    levy_beta=1.5,
                    alpha_max=0.5,
                    alpha_min=0.05,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=0,
                    post_polish=True,
                    search_limits=SearchLimitsInput(x_min=2.5, x_max=40.0),
                ),
            ),
        ),
        benchmark_fos=2.11168,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cuckoo_global_search_benchmark",
        analysis_method="spencer",
        search_method="cuckoo_global_circular",
        name="Case 3 (Spencer Cuckoo Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cuckoo_global_circular",
                cuckoo_global_circular=CuckooGlobalSearchInput(
                    population_size=40,
                    max_iterations=200,
                    max_evaluations=5000,
                    discovery_rate=0.20,
                    levy_beta=1.5,
                    alpha_max=0.5,
                    alpha_min=0.05,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=0,
                    post_polish=True,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        benchmark_fos=0.985334,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cuckoo_global_search_benchmark",
        analysis_method="spencer",
        search_method="cuckoo_global_circular",
        name="Case 4 (Spencer Cuckoo Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cuckoo_global_circular",
                cuckoo_global_circular=CuckooGlobalSearchInput(
                    population_size=50,
                    max_iterations=250,
                    max_evaluations=7000,
                    discovery_rate=0.20,
                    levy_beta=1.5,
                    alpha_max=0.5,
                    alpha_min=0.05,
                    min_improvement=1e-4,
                    stall_iterations=30,
                    seed=0,
                    post_polish=True,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        benchmark_fos=1.23141,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cmaes_global_search_benchmark",
        analysis_method="spencer",
        search_method="cmaes_global_circular",
        name="Case 2 (Spencer CMAES Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=7.5, l=15.0, x_toe=10.0, y_toe=10.0),
            material=MaterialInput(gamma=20.0, c=20.0, phi_deg=20.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=7,
                tolerance=0.005,
                max_iter=50,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cmaes_global_circular",
                cmaes_global_circular=CmaesGlobalSearchInput(
                    max_evaluations=4500,
                    direct_prescan_evaluations=600,
                    cmaes_population_size=8,
                    cmaes_max_iterations=180,
                    cmaes_restarts=2,
                    cmaes_sigma0=0.15,
                    polish_max_evaluations=80,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=1,
                    post_polish=True,
                    invalid_penalty=1e6,
                    nonconverged_penalty=1e5,
                    search_limits=SearchLimitsInput(x_min=2.5, x_max=40.0),
                ),
            ),
        ),
        benchmark_fos=2.11168,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cmaes_global_search_benchmark",
        analysis_method="spencer",
        search_method="cmaes_global_circular",
        name="Case 3 (Spencer CMAES Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=10.0, l=20.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=20.0, c=3.0, phi_deg=19.6),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cmaes_global_circular",
                cmaes_global_circular=CmaesGlobalSearchInput(
                    max_evaluations=5500,
                    direct_prescan_evaluations=800,
                    cmaes_population_size=8,
                    cmaes_max_iterations=200,
                    cmaes_restarts=2,
                    cmaes_sigma0=0.15,
                    polish_max_evaluations=100,
                    min_improvement=1e-4,
                    stall_iterations=25,
                    seed=1,
                    post_polish=True,
                    invalid_penalty=1e6,
                    nonconverged_penalty=1e5,
                    search_limits=SearchLimitsInput(x_min=20.0, x_max=70.0),
                ),
            ),
        ),
        benchmark_fos=0.985334,
        margin=0.01,
    ),
    GlobalSearchBenchmarkVerificationCase(
        case_type="cmaes_global_search_benchmark",
        analysis_method="spencer",
        search_method="cmaes_global_circular",
        name="Case 4 (Spencer CMAES Global Search Benchmark)",
        project=ProjectInput(
            units="metric",
            geometry=GeometryInput(h=20.0, l=25.0, x_toe=30.0, y_toe=25.0),
            material=MaterialInput(gamma=16.0, c=9.0, phi_deg=32.0),
            analysis=AnalysisInput(
                method="spencer",
                n_slices=25,
                tolerance=0.0001,
                max_iter=100,
                f_init=1.0,
            ),
            prescribed_surface=None,
            search=SearchInput(
                method="cmaes_global_circular",
                cmaes_global_circular=CmaesGlobalSearchInput(
                    max_evaluations=7000,
                    direct_prescan_evaluations=1200,
                    cmaes_population_size=10,
                    cmaes_max_iterations=250,
                    cmaes_restarts=3,
                    cmaes_sigma0=0.15,
                    polish_max_evaluations=120,
                    min_improvement=1e-4,
                    stall_iterations=30,
                    seed=1,
                    post_polish=True,
                    invalid_penalty=1e6,
                    nonconverged_penalty=1e5,
                    search_limits=SearchLimitsInput(x_min=10.0, x_max=95.0),
                ),
            ),
        ),
        benchmark_fos=1.23141,
        margin=0.01,
    ),
)

VERIFICATION_CASES = VERIFICATION_CASES + SPENCER_VERIFICATION_CASES
